import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Your global CSS
import { FluentProvider, teamsLightTheme } from "@fluentui/react-components";
 
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      {/* <link
  rel="stylesheet"
  href="https://res-1.cdn.office.net/files/fabric-cdn-prod_20230815.002/office-ui-fabric-core/11.1.0/css/fabric.min.css"
/> */}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gridlex/2.7.1/gridlex.min.css"></link>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
