
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Your global CSS


import MasterContainer from "./config/MasterContainer";

import { FluentProviders } from "./FluentProviders";
import { Providers } from "./Providers";







const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gridlex/2.7.1/gridlex.min.css"></link>
      </head>



      <body>
       
          <Providers>
            <MasterContainer>

            <FluentProviders>{children}</FluentProviders>
            </MasterContainer>


          </Providers>
        

      </body>

    </html>
  );
}
