
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Your global CSS
import { FluentProvider, teamsLightTheme } from "@fluentui/react-components";
import { Provider } from "react-redux";
import store from "./config/redux/store";
import { Providers } from "./providers";
import Login from "./login/page";
import MasterContainer from "./config/MasterContainer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gridlex/2.7.1/gridlex.min.css"></link>
      </head>



      <body>
        <Providers>
          <MasterContainer>
            
            {children}
            </MasterContainer>


        </Providers>
      </body>

    </html>
  );
}
